Retry staging due to random gotestsum issue again
The staging test of 2 targets failed (Ubuntu-focal, centos-8) due to:
  gotestsum: /lib/powerpc64le-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by gotestsum)
Fedora-37 failed too:
  Error: Failed to download metadata for repo 'docker-ce-stable': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried